In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [7]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns = ['has_covid']),df['has_covid'],test_size = 0.2)

In [10]:
X_train

age  gender  fever   cough       city
4    65  Female  101.0    Mild     Mumbai
59    6  Female  104.0    Mild    Kolkata
5    84  Female    NaN    Mild  Bangalore
38   49  Female  101.0    Mild      Delhi
84   69  Female   98.0  Strong     Mumbai
..  ...     ...    ...     ...        ...
64   42    Male  104.0    Mild     Mumbai
30   15    Male  101.0    Mild      Delhi
93   27    Male  100.0    Mild    Kolkata
46   19  Female  101.0    Mild     Mumbai
66   51    Male  104.0    Mild    Kolkata

[80 rows x 5 columns]

# Aam Zindagi

In [11]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever

array([[101.        ],
       [104.        ],
       [101.02777778],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [101.        ],
       [101.02777778],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [102.        ],
       [102.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [102.        ],
       [101.02777778],
       [100.        ],
       [103.        ],
       [103.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [103.        ],
       [101.02777778],
       [103.        ],
       [ 98

In [12]:
# Adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [13]:
# ordinalEncoding 
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [17]:
# OneHotEncoding
ohe = OneHotEncoder(drop = 'first',sparse_output = False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
# for test set
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],


In [18]:
X_train_gender_city.shape

(80, 4)

In [19]:
# Extract Age
X_train_age = X_train.drop(columns = ['gender','fever','cough','city']).values

# for test data
X_test_age = X_test.drop(columns = ['gender','fever','cough','city']).values
X_train_age.shape

(80, 1)

In [20]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# Mentos Zindagi

In [25]:
from sklearn.compose import ColumnTransformer

In [26]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [29]:
transformer.fit_transform(X_train)

array([[101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   6.        ],
       [101.02777778,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  69.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  74.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.    

In [27]:
transformer.fit_transform(X_train).shape

(80, 7)

In [28]:
transformer.transform(X_test).shape

(20, 7)